### ISSUE TITLE
Task list (first sprint)

### ISSUE THREAD

**Issue by jeanpierrethach** [jeanpierrethach/FreeFlow-Grid-Solver-#1]
### Priority #1

- [x] Add play and quit menu before loading the level.

- [x] When the user tries to link the same two color origin grid case, it has to be fully connected.

- [x] If the user clicks on the origin, the cases going forward that path must be cleared.

- [x] If the user clicks on a case from a path, the cases going forward that path must be cleared.

- [x] If the user overrides a path with another path and then clicks to clear the path forward from the path overrided, it has to only clear his path.

- [x] Restrict diagonal path.

- [x] If the user moves pass the first origin after creating a path, disallow the creation of path pass that origin.

- [x] If the user moves pass the second origin after creating a path, disallow the creation of path pass that origin.

- [x] If the user moves on an origin, its case will be highlighted and will not be available to be linked unless he resets the origin. 

### Priority #2

- [x] Allow the user to move back from cases created for a path.

- [x] If the users tries to create a path that goes pass another path, the path already established has to keep its cases until the point of collision.

- [x] If the users tries to create a path at the end of another path, only clear that case.

- [x] If the users tries the step above and move his cursor backwards to the original path, it shouldn't clear the cases.

- [x] **Path 1 Red, Path 2 Blue.** 
If the user create Path 1 and cuts on the Path 2 and then recreates Path 1 onto the end case of Path 2, the logic of clearing that case only should be applied.

- [x] If the users clicks on an origin, all path created must be from that point.
**(Functionality to adjust : Moving to another origin of the same color resets its origin to the new one)** 

### Priority #3

Moved to second sprint #2 

### List of completed tasks before the listing

-  Draw a static grid
-  Add a static level
-  Add visual effects on user action
-  Restrict mouse movement to the current window
-  Allow line drawing from origin grid cases
