### ISSUE TITLE
Task list(second sprint)

### ISSUE THREAD

**Issue by jeanpierrethach** [jeanpierrethach/FreeFlow-Grid-Solver-#2]
## Priority #1 

- [x] Modulate mouse event listeners.

- [x] Allow dynamic resizing for the grid, lines and ellipses. **(With height and width variables in mainwindow.h)**

- [x] Read data from JSON files or any other format allowed. 
 **The previous implementation only reads from a stringstream object that replicates a JSON file. It has to read from a JSON file.** 
**The current implementation reads from a JSON file using QT classes.**

- [x] Generate color palettes for the level generator. **(Not implemented: Keep a count of the amount of origins generated to parameterize generateColorPalette function and reduce nbOfColors generated)**

- [x] Set levels from the data.

- [x] Allow the user to save a game.

- [x] Allow the user to load a saved game.

- [x] Add path verification algorithm.

- [x] Allow user to play against an AI. (generate a random level of X format that can be solve)

- [x] Clear paths from generated level.

- [x] Change matrix pos into method

- [x] Dynamically create 2d array according to the level JSON file.

- [x] Allow the user to go back to the level selection.

- [x] Modulate project.

- [x] Refactor/rename Path into Cell.

## Priority #2

- [x] Allow the user to restart the current level.

- [x] Allow the user to go back to the main screen.

- [x] Implement our own push buttons and dynamically position and resize itself according to mainwindow frame.

## Priority #3 
Moved to #4
