### ISSUE TITLE
Task list (Third sprint)

### ISSUE THREAD

**Issue by jeanpierrethach** [jeanpierrethach/FreeFlow-Grid-Solver-#4]
## Priority #1

- [ ] Allow user to create level. 

- [ ] Modify load implementation to allow loading file from any repositories.

- [ ] Differentiate json file from a generated level/defined level to a user-created level (Loading slot).

- [x] Add path resolution algorithm. **(Partially complete)**

- [ ] Allow the user to choose his level and difficulty.

## Priority #2

- [ ] At odd grid size, the painter inside the grid cases is off a little bit. (Change int to double)

- [ ] Allow offset changes on the left, top, right, bottom side for the grid frame.

- [ ] Deallocate memory when possible and fix memory leaks. 
**(gridbuilder class, clear() method, pointers, etc.)**
Memory leak (Path* next[1], previous[1], delete grid, etc.)

- [ ] Refactor/clean up code.

- [ ] Path* (setter), grid->getGrid[][]...
